### DISCUSSION TITLE
Support a new view where you can see multiple sections at once

### DISCUSSION THREAD

**Discussion by dlvhdr** [dlvhdr/gh-dash#241] [General]
I'd like to introduce a new feature to `gh-dash` that I call "Dashboards".
It will basically allow you to view several sections at once.
> As a reminder, a section is defined by a title and a GitHub search query.

The thing I'm missing right now, is the ability to see my immediate tasks when I open `gh-dash`. To solve that I could create a "My PRs" + "Needs My Review" dashboard.
Also, for the `gh-dash` project, I would like a dashboard that will display the "Open PRs" and "Open Issues".

I've made a mock that shows how this might look like:
![image](https://user-images.githubusercontent.com/6196971/223524455-22e22b61-8727-4dfb-a566-ae576b738446.png)

As for the `config.yml`, I was thinking of something like this:
```yaml
dashboards:
  - title: Immediate Feedback
    sections:
      - title: Created
        filters: is:pr -org:wix-private author:@me
        layout:
          author:
            hidden: true
      - title: Review Requested
        filters: is:pr review-requested:@me
      - title: Commented
        filters: is:pr commenter:@me
        limit: 5
```

I'm really looking for feedback on the concept, design and `config.yml`.
