### DISCUSSION TITLE
Failed to find local path for repo

### DISCUSSION THREAD

**Discussion by danielb2** [dlvhdr/gh-dash#284] [General]
I have the following keybinding

```
keybindings:
  issues:
    - command: gh issue develop {{ .IssueNumber }} -c
      key: C
```

but when I press <kbd>C</kbd> on an issue, I get the error `󰅙 Failed to find local path for repo [org]/[repo]`

what have I done wrong?
