### DISCUSSION TITLE
How do i unbind a key?

### DISCUSSION THREAD

**Discussion by pbsds** [dlvhdr/gh-dash#311] [Q&A] [answered]
How do i unbind a key?

**Comment by ja-godfrey** [comment, marked as answer]
Keybindings are configured in your config.yml (global config is typically `$HOME/.config/gh-dash/config.yml` on macOS/Linux or `%USERPROFILE%\.config\gh-dash\config.yml` on Windows). So if you can just delete the key you want to unbind in the YAML.

If you mean “disable a built-in default binding”: there isn’t a dedicated “unbind” flag—dash supports overriding bindings and adding custom ones. A practical workaround is to override the same key with a harmless no-op command.

Example (override `x` to do nothing):

```yaml
 keybindings:
   universal:
     - key: x
       name: noop
       command: "true"
```

On Windows, if `true` isn’t available in your shell, use:

```yaml
 keybindings:
   universal:
     - key: x
       name: noop
       command: "cmd /c exit 0"
```

That effectively “unbinds” the key by replacing the action with a no-op.
