### DISCUSSION TITLE
Can I use modifiers (such as CTRL) in key bindings?

### DISCUSSION THREAD

**Discussion by ckagerer** [dlvhdr/gh-dash#509] [Q&A] [answered]
I have tried it with such a configuration. But it does not work.

```yaml
keybindings:
  prs:
    - key: Ctrl+O
      builtin: checkout
```

Does anyone have any idea if it should work or if it needs to be configured differently?
Unfortunately I have not found anything in the configuration or in the issues.

Thank you for your help.
Best regards
Christian
