### DISCUSSION TITLE
Problems with layout

### DISCUSSION THREAD

**Discussion by seancallanan** [dlvhdr/gh-dash#528] [General]
I am having issues changing the layout for prs.  I have this in my ~/.config/gh-dash/config.yml:

```
defaults:
  preview:
    open: true
    width: 1000
  prsLimit: 30
  issuesLimit: 20
  view: prs
  layout:
    prs:
      repo:
        width: 20
      author:
        width: 15
```

But it has not affect, I still get the default.  Note: it picks up the defaults.preview.width value so I think it is finding the correct yml file.

I have also tried to add a layout in the prSections for a given filter but that did not work either.  I don't see anyone online having issues with this so it must be user error on my part.  Can anyone see the mistake I am making?

Thanks for your help
