### ISSUE TITLE
Suggestion: Be more specific on font suggestion

### ISSUE THREAD

**Issue by pkutaj** [dlvhdr/gh-dash#101]
* I suggest being more specific with the name of the font rendering symbols: MesloLGL Nerd Font Mono from [ryanoasis/nerd-fonts: ](https://github.com/ryanoasis/nerd-fonts) does the trick for me. Besides, thanks for the great work!

**Comment by dlvhdr** [comment]
@pkutaj I'm using these fonts:
```
font:
  normal:
    family: FiraCode Nerd Font
    style: Light
  bold:
    family: FiraCode Nerd Font
    style: Regular
  italic:
    family: VictorMono Nerd Font
    style: Light Oblique
```
I'll update the README
