### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jcornaz** [dlvhdr/gh-dash#153]
**Describe the bug**

The keybindings do not work.

**To Reproduce**

Use the following `~/.config/gh-dash/config.yml`:

```yaml
prSections:
- title: All
  filters: repo:dlvhdr/gh-dash
keybindings:
  prs:
    - key: c
      command: cd {{.RepoPath}}; gh pr checkout {{.PrNumber}}
repoPaths:
  dlvhdr/gh-dash ~/Desktop/gh-dash
```

Execute:
```sh
cd ~/Desktop
gh repo clone dlvhdr/gh-dash
gh dash
```

Select any PR and press `c`. -> Nothing happens.

**Expected behavior**

With the configuration above (which is taken from the readme), pressing `c` should close `gh-dash`, `cd` into the repo directory and check out the pull-request.

**Desktop (please complete the following information):**
 - OS: Linux (Manjaro) x64
