### ISSUE TITLE
Support selecting which fields will be displayed for each section

### ISSUE THREAD

**Issue by micalevisk** [dlvhdr/gh-dash#30]
I think it would be really cool if we can configure which columns will appear (except for `Title` of course).

## Scenario

Let's say I have this config:

```yml
- title: My PRs on my main project
  filters: author:@me repo:what/ever
```

then the `Author` and `Repo` columns are pretty useless for this tab. Also, since the list is sorted by `Updated At` field, one may doesn't care about that info at all. These (and maybe other information that your extension could show in the future) just pollute my reading.

| Title | CI | Lines | Author | Repo | Updated At |
| - | - | - | - | - | - |

## Possible approach

Support an optional case insensitive `fields` property  for each section, like:

```yml
- title: My PRs on my main project
  filters: author:@me repo:what/ever
  fields:
    - ci
    - updated at
```

then only `Title`, `CI` and `Updated At` will be display in that section.

| Title | CI | Updated At |
| - | - | - |
