### ISSUE TITLE
Variables in config file

### ISSUE THREAD

**Issue by rtalexk** [dlvhdr/gh-dash#390]
**Is your feature request related to a problem? Please describe.**

I'm using different configs per repository. I want to add them to my dotfiles without leaking org or repo names.

**Describe the solution you'd like**

It would be cool if I could do something like this

```yml
prSections:
  - title: Open
    filters: repo:{{org}}/{{repo}} is:open

  - title: Requested
    filters: repo:{{org}}/{{repo}} is:open user-review-requested:@me

  - title: Reviewing
    filters: repo:{{org}}/{{repo}} is:open commenter:@me
```

It would check if the cwd is a git repo, if so replace `{{...}}` by the actual vlaue.

**Describe alternatives you've considered**

Not sure if there's a workaround for this, but I've thought about having a config like the one above and create a script so that on-the-fly I replace all `{{these}}` and write the result to a temp file, then use this temp file as the config for GH Dash.

May work, but seems too much.
