### ISSUE TITLE
Count badge in Tabs

### ISSUE THREAD

**Issue by rtalexk** [dlvhdr/gh-dash#400]
**Is your feature request related to a problem? Please describe.**

When you are in a given tab, you have to navigate to others to see if there are results.

**Describe the solution you'd like**

An option to display the number of results would be useful, and even better if you can format the tab title, i.e:

```yml
prSections:
  - title: Open ({{ count }})
    filters: repo:org/repo is:open -is:draft
```

Would give something like ` | Open (5) | Other tab | ... `

Or even as a global setting for all the tabs (PRs/Issues).
