### ISSUE TITLE
[BUG] Merging fails with v4.5.3

### ISSUE THREAD

**Issue by Arkoprabho** [dlvhdr/gh-dash#418]
**Describe the bug**
Merging a PR fails with the latest version. I have tried it on PRs with multiple merge styles, Rebase and Merge, Squash and Merge etc.

**To Reproduce**
- A mergeable PR on `gh dash`
- Press `m` to initiate merge. Confirm merge
- Error message received `2024/08/14 12:04:36 ERRO Task finished with error id=pr_merge_488 err="exit status 1"`
- Install version v4.5.2, and following the same steps behaves as intended and the PR is merged

**Expected behavior**
Pressing `m` on a PR should merge the PR

**Screenshots**
Confirmation screenshot:
![Screenshot 2024-08-14 at 12 09 39 PM](https://github.com/user-attachments/assets/642cac0b-7b36-41ed-8340-7986ee83968d)
Error message screenshot: 
![Screenshot 2024-08-14 at 12 10 25 PM](https://github.com/user-attachments/assets/abc73a71-547b-4a87-b3d5-1686d8e1693c)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - Model: Macbook Pro, M1 Pro
 - Memory: 16GB

**Comment by Arkoprabho** [comment]
PS. Here's my config:
```yml
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths: {}
pager:
  diff: delta

```
