### ISSUE TITLE
[BUG] Can't map preview page up/down to pgup/pgdn keys

### ISSUE THREAD

**Issue by danmou** [dlvhdr/gh-dash#465]
**Describe the bug**
Mapping `pgup` to `builtin: pageUp` and `pgdn` to `builtin: pageDown` has no effect, the keys do nothing. Mapping them to something else works, so the problem is not in receiving the key events.

**To Reproduce**
1. Add this to your config:
```yaml
keybindings:
  universal:
    - key: pgup
      builtin: pageUp
    - key: pgdn
      builtin: pageDown
```
2. Open `gh dash` and try pressing pgup/pgdown

**Expected behavior**
The preview pane scrolls up and down

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Side note**
It was difficult to find the list of supported keys and their string representations. In the end I tracked it down [here](https://github.com/charmbracelet/bubbletea/blob/6e71f52a8add0fdeba202d4e1bdd289182b156ac/key.go#L260-L350) by looking through the code.
