### ISSUE TITLE
Update with Rebase

### ISSUE THREAD

**Issue by alcpereira** [dlvhdr/gh-dash#485]
**Is your feature request related to a problem? Please describe.**
At work, we use rebase on 80% of the repos, and I want to avoid as much as possible having those merge commits due to the Update feature.

**Describe the solution you'd like**
The possibility to use "Update with Rebase" that is already available in the GH CLI ([here](https://cli.github.com/manual/gh_pr_update-branch)). 

**Describe alternatives you've considered**

I started working on an implementation but I would like to have some feedback regarding what would be better:
- Another keybinding: `u` does update with merge commit, `U` does update with rebase
- A config (global? repo scoped?) to override the default behaviour of `u`
- A prompt asking if you want to use merge or rebase (similar to lazygit when you do rebase)

**Comment by dlvhdr** [comment]
I guess another option is to contribute to gh to add interactivity similar to how the approve and merge commands work. 
But I'm also ok with adding a global config option to set a default.

**Comment by ckagerer** [comment]
Hey @alcpereira ,

I use custom keybindings for this:

```yml
keybindings:
  prs:
  - command: gh pr update-branch {{.PrNumber}} --rebase --repo {{.RepoName}}
    key: u
  - command: gh pr update-branch {{.PrNumber}} --repo {{.RepoName}}
    key: U
```
