### ISSUE TITLE
[BUG] Failed to parsetemplate

### ISSUE THREAD

**Issue by kapral18** [dlvhdr/gh-dash#496]
**Describe the bug**
Getting a parsetemplate error when trying to invoke a custom command

**To Reproduce**
Apply config with this keybinding:

```yaml
keybindings:
  issues:
    - key: e
      command: >
        tmux new-window -c {{.RepoPath}} "nvim -c \":silent Octo issue edit {{.IssueNumber}}\""
```

1. Go to issues view
2. Hit e
3. See error

I tried all combinations of quotes single double and in between, result is the same

**Expected behavior**
No error and command executed

**Screenshots**
![image](https://github.com/user-attachments/assets/18c54790-63a9-4fa8-a67b-302204a98056)

**Desktop (please complete the following information):**
 - OS: Mac 15.2
