### ISSUE TITLE
Don't know if Bug or I'm stewpid

### ISSUE THREAD

**Issue by Nino678190** [dlvhdr/gh-dash#522]
I tried to add my own Categorie for Issues to the config file. Now it won't start.

```
Sections:
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: Involved
  filters: is:open involves:@me -author:@me
  type: null
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
-title: Important
  filters: is:open involves:@me label:Important

```

The last one is my own. The crash message was:
```shell
2025-02-05T15:42:53+01:00 FATA <ui/ui.go:114> Reading config file: failed parsing config file location="" err="failed parsing config.yml: yaml: line 19: mapping values are not allowed in this context"
```

**Comment by AbbasDehganzadeh** [comment]
Hey, friend
I'm so happy for my first contrib. to open-source ;-)
So, I'm here to help you

Fortunetaly: the solution is simple
there is a little mistake in line 18

``` yaml
Sections:
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: Involved
  filters: is:open involves:@me -author:@me
  type: null
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
- title: Important
  filters: is:open involves:@me label:Important
```

If it doesn't work, don't hesitate to ask me 😃.
